name: flame_state_machine
description: A lightweight, type-safe state machine for the Flame game engine, enabling modular and reusable behavior for Flame components.
version: 2.0.3
repository: https://github.com/bszarlej/flame_state_machine
issue_tracker: https://github.com/bszarlej/flame_state_machine/issues
topics:
  - flame
  - state-machine
  - game-development
  - game-engine
  - dart

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.30.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=5.0.0 <7.0.0"
  test: ^1.25.15
  